### PR TITLE
Add darkloading mode

### PR DESCRIPTION
**Pull request by steffengr**
Add darkloading mode in which commands are execuded but there results
are not taken into consideration.

### CODE REVIEW

**Comment by xeago** [comment]
+1

**Comment by jstck** [comment]
+1, YOLO.

**Comment by Cy6erBr4in** [comment]
if I understand it correctly this is a very simple implementationi where s3mper will definitely affect performance of list operations, also I don't see that you have introduced any safety measures, e.g. a try/catch around everything, so for me it doesn't seem to be a proper darkload in this case since the normal operation can fail because of s3mper which is exactly what we want to avoid by darkloading, isn't it?

**Comment by xeago** [comment]
@Cy6erBr4in there's a [try-catch already](https://github.com/spotify/s3mper/pull/10/files#diff-e5c3ca82d0e6a04661af0cc62133a1e5R382), we've taken care to make sure the `shouldFail` method is configured to not cause failures.

**Comment by Cy6erBr4in** [comment]
:+1:

**Pull request merged**
